export { TrustAuthority } from './TrustAuthority';
export { AcademicExcellence } from './AcademicExcellence';
export { InfrastructureFacilities } from './InfrastructureFacilities';
export { FacultyStudentCare } from './FacultyStudentCare';
export { HolisticDevelopment } from './HolisticDevelopment';
export { Testimonials } from './Testimonials';
export { AdmissionCTA } from './AdmissionCTA';
export { Highlights } from './Highlights';
export { HomeInfoSection } from './HomeInfoSection';
